# -*- coding: utf-8 -*-
# Created by Luis Enrique Fuentes Plata

version: "3.7"

networks:
  default:
    driver: bridge
    name: ${NETWORK_NAME}
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}

services:

  # db
  db:
    image: postgres:${POSTGRES_VERSION}
    container_name: db
    restart: on-failure
    ports: 
      - "5432:5432"
    environment: 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./.postgres/initdb.d:/docker-entrypoint-initdb.d/
    command: 
      - postgres
      - "-c"
      - "max_connections=150"

  # Web Server
  python:
    image: webapp:latest
    container_name: my_app
    restart: on-failure
    ports: 
      - "8080:80"
    environment:
      - PORT=80
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on: 
      - db